package com.demo.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name="UserTable")
public class MyUser 
{
	@Id
	//the pid values will be autogenerated
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name="uid")
	private int uid;
	
	@Column(name="uname",nullable=false,unique=true)
	private String uname;

	private double usal;
	
	
	public MyUser( String uname, double usal) {
		super();
	
		this.uname = uname;
		this.usal = usal;
	}
	public MyUser() {
	
	}
	public int getUid() {
		return uid;
	}
	public void setUid(int uid) {
		this.uid = uid;
	}
	public String getUname() {
		return uname;
	}
	public void setUname(String uname) {
		this.uname = uname;
	}
	public double getUsal() {
		return usal;
	}
	public void setUsal(double usal) {
		this.usal = usal;
	}
	@Override
	public String toString() {
		return "MyUser [uid=" + uid + ", uname=" + uname + ", usal=" + usal + "]";
	}
	
	
	
	
	
}
